version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-node-api
    command: yarn start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - "3333:3333"
    links:
      - mongo
